In [1]:
import pandas as pd

In [41]:
data = pd.read_excel("rekap_data_terorisme_loc_v4.xlsx")

In [42]:
data.head()

,File_Name,case_id,what_case_number,what_court_name,what_court_level,what_charged_articles,what_indictment_model,what_proven_offense,what_verdict_per_charge,what_appellate_outcome,...,why_mitigating_factors,why_radicalization_sources,why_motivation_factors,how_much_prison_term,how_much_injury_severity,what_detention_credit,where_detention_location,how_much_monetary_penalties,how_much_seized_money_amount,when_indictment_date
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,02/Pid. Sus./2014/PN. Jkt. Ut,02/Pid. Sus./2014/PN. Jkt. Ut,Pengadilan Negeri Jakarta Utara,pertama,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...,Alternatif,permufakataan jahat dengan sengaja melakukan k...,Terbukti,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1005_PID~SUS_2020_PN JKT~BRT.json,1005/Pid. Sus/2020/PN. Jkt. Brt,1005/Pid. Sus/2020/PN. Jkt. Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,kajian ustadz MUHLIS\n---\nFacebook\n---\ntele...,NaN,Years: 3 | Months: 6,Tidak ada korban,NaN,NaN,NaN,NaN,NaN
2,1006_PID~SUS_2020_PN JKT~BRT.json,1006/Pid. Sus/2020/PN. Jkt. Brt,1006/Pid. Sus/2020/PN. Jkt. Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,grup Media Sosial Whats App MENITI TAUHID\n---...,NaN,Years: 3 | Months: 6,Tidak ada korban,True,NaN,NaN,NaN,NaN
3,1012_PID~SUS_2021_PN JKT~TIM.json,1012 Pid. SUS/2021/PN. Jkt. Tim,1012 Pid. SUS/2021/PN. Jkt. Tim,Pengadilan Negeri Jakarta Timur sejak,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,NaN,Tindak Pidana Terorisme,Terbukti,NaN,...,Terdakwa bersikap sopan dipersidangan\n---\nTe...,kajian Diniyah di Mushola daerah Ds. Pondok Su...,keinginan untuk hidup dibawah naungan Negara S...,Years: 3 | Months: 6,Tidak ada korban,NaN,Rumah Tahanan Negara (RUTAN),NaN,NaN,NaN
4,1014_PID~SUS_2021_PN JKT~TIM.json,1014/Pid. Sus/2021/PN Jkt. Tim,1014/Pid. Sus/2021/PN Jkt. Tim,Pengadilan Negeri Jakarta Timur,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Kombinasi,tindak pidana Terorisme dan Pendanaan Terorisme,Primair: Terbukti,NaN,...,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,NaN,NaN,Years: 4 | Months: 6,Tidak ada korban,True,NaN,50.000.000,NaN,NaN

In [31]:
data.columns

Index(['File_Name', 'case_id', 'what_case_number', 'what_court_name',
       'what_court_level', 'what_charged_articles', 'what_indictment_model',
       'what_proven_offense', 'what_verdict_per_charge',
       'what_appellate_outcome', 'what_evidence_items',
       'what_evidence_disposition', 'what_defense_plea',
       'what_pelatihan_activities', 'what_perencanaan_activities',
       'what_tindakan_activities', 'when_appeal_timeline', 'when_arrest_date',
       'when_crime_time_range', 'when_detention_timeline',
       'where_district_court', 'who_defendants', 'who_co_defendants',
       'who_defense_counsels', 'who_investigators', 'who_judges', 'who_clerk',
       'who_prosecutors', 'who_witnesses', 'why_reasoning_evidence',
       'why_reasoning_appeal', 'how_many_witness_count',
       'how_many_charge_count', 'how_many_defendant_count',
       'how_many_evidence_item_count', 'what_has_attack_plan',
       'what_attack_preparation_activities', 'what_attack_plan_summary',
       'what_defendant_chat_platform', 'when_district_court_date',
       'when_defendant_local_network_joined_at', 'where_court_location',
       'where_activity_locations', 'where_crime_location',
       'where_arrest_location', 'who_defendant_ideology_affiliation',
       'who_defendant_local_network', 'who_related_entities',
       'why_aggravating_factors', 'why_mitigating_factors',
       'why_radicalization_sources', 'why_motivation_factors',
       'how_much_prison_term', 'how_much_injury_severity',
       'what_detention_credit', 'where_detention_location',
       'how_much_monetary_penalties', 'how_much_seized_money_amount',
       'when_indictment_date'],
      dtype='str')

In [44]:
data.loc[
    data["who_defendant_ideology_affiliation"].isna() |
    (
        data["who_defendant_ideology_affiliation"]
        .str.lower()
        .str.strip() == "tidak diketahui"
    ),
    "who_defendant_local_network"
] = None

In [45]:
data.to_excel("rekap_data_terorisme_loc_v4.xlsx", index=False)

In [43]:
len(data.columns)

59

In [33]:
df_filtered = data[["who_defendant_ideology_affiliation", "File_Name", "what_charged_articles", "who_defendant_local_network"]]
df_filtered.head()

,who_defendant_ideology_affiliation,File_Name,what_charged_articles,who_defendant_local_network
0,NaN,02_PID~ SUS~_2014_PN~JKT~ UT~.json,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...,NaN
1,Daulah Islamiyah/ISIS,1005_PID~SUS_2020_PN JKT~BRT.json,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...,Klinik Rukiah Kota Padang (Halaman 4)
2,Kelompok ISIS,1006_PID~SUS_2020_PN JKT~BRT.json,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...,Kediri Jawa Timur (Halaman 5)
3,Jamaah Islamiyah (JI),1012_PID~SUS_2021_PN JKT~TIM.json,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Klaten (Halaman 4)
4,Jamaah Islamiyah (JI),1014_PID~SUS_2021_PN JKT~TIM.json,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Jawa Tengah (Halaman 5)

In [ ]:
unknown_ideology = df_filtered[
    (df_filtered["who_defendant_ideology_affiliation"] == "Tidak Diketahui") |
    (df_filtered["who_defendant_ideology_affiliation"].isna())
]

print(len(unknown_ideology))

99

In [35]:
unknown_ideology.tail(13)

,who_defendant_ideology_affiliation,File_Name,what_charged_articles,who_defendant_local_network
441,NaN,79K_PM~I04_AD_X_2020.json,Pasal 1 ayat (1) UU RI Darurat No. 12 tahun 19...,Palembang
442,NaN,79_PID~SUS_2015_PN MLN.json,Pasal 112 ayat (1) UU Nomor 35 Tahun 2009 tent...,NaN
443,NaN,7_PID~SUS_2011_PT~PR.json,Pasal 114 ayat 1 UU Nomor 35 Tahun 2009 tentan...,NaN
448,Tidak Diketahui,807 K_PID~SUS_2011.json,Pasal 15 UU Terorisme,NaN
449,Tidak Diketahui,80_PID_2012_PT~BTN.json,Pasal 14 jo. Pasal 7 UU No. 15 Tahun 2003 Tent...,Bima (Halaman 15)
462,NaN,84_PID~SUS_2015_PN~TBK~.json,Pasal 112 Ayat (1) UU Nomor 35 tahun 2009 tent...,NaN
463,NaN,85_PID~SUS_2021_PN KLB.json,NaN,NaN
467,Tidak Diketahui,878_PID~SUS_2021_PN JKT~TIM.json,Pasal 363 Ayat (1) ke-4 KUHP,NaN
468,Tidak Diketahui,893 K_PID~SUS_2009.json,Pasal 6 UU No. 15 Tahun 2003\n---\nPasal 55 ay...,Polewali Mandar (Halaman 1)
469,Tidak Diketahui,8_PID~B_2022_PN SBH.json,Pasal 335 ayat (1) angka 1 KUHP idana,NaN
470,Tidak Diketahui,904 K_PID~SUS_2009.json,Pasal 6 Undang-Undang RI Nomor.15 Tahun 2003 t...,Sulawesi Barat (Halaman 1)
475,NaN,939_PID~SUS_2012_PN~DPS.json,Pasal 114 ayat (1) UU RI No.35 Tahun 2009 tent...,NaN
500,NaN,99_PID_SUS_2016_PN_SDN.json,Pasal 112 ayat (1) UU RI No. 35 Tahun 2009 Ten...,NaN

In [36]:
df_filtered.loc[
    df_filtered["who_defendant_ideology_affiliation"].isna() |
    (
        df_filtered["who_defendant_ideology_affiliation"]
        .str.lower()
        .str.strip() == "tidak diketahui"
    ),
    "who_defendant_local_network"
] = None

In [37]:
df_filtered.head()

,who_defendant_ideology_affiliation,File_Name,what_charged_articles,who_defendant_local_network
0,NaN,02_PID~ SUS~_2014_PN~JKT~ UT~.json,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...,NaN
1,Daulah Islamiyah/ISIS,1005_PID~SUS_2020_PN JKT~BRT.json,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...,Klinik Rukiah Kota Padang (Halaman 4)
2,Kelompok ISIS,1006_PID~SUS_2020_PN JKT~BRT.json,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...,Kediri Jawa Timur (Halaman 5)
3,Jamaah Islamiyah (JI),1012_PID~SUS_2021_PN JKT~TIM.json,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Klaten (Halaman 4)
4,Jamaah Islamiyah (JI),1014_PID~SUS_2021_PN JKT~TIM.json,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Jawa Tengah (Halaman 5)

In [38]:
unknown_ideology = df_filtered[
    (df_filtered["who_defendant_ideology_affiliation"] == "Tidak Diketahui") |
    (df_filtered["who_defendant_ideology_affiliation"].isna())
]

print(len(unknown_ideology))

99

In [39]:
unknown_ideology.to_excel("unknown_ideology4.xlsx", index=False)

## Mitigating and Aggravating

In [46]:
data = pd.read_excel("rekap_data_terorisme_loc_v4.xlsx")
data.head()

,File_Name,case_id,what_case_number,what_court_name,what_court_level,what_charged_articles,what_indictment_model,what_proven_offense,what_verdict_per_charge,what_appellate_outcome,...,why_radicalization_sources,why_motivation_factors,how_much_prison_term,how_much_injury_severity,what_detention_credit,where_detention_location,how_much_monetary_penalties,how_much_seized_money_amount,when_indictment_date,who_defendant_local_network
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,02/Pid. Sus./2014/PN. Jkt. Ut,02/Pid. Sus./2014/PN. Jkt. Ut,Pengadilan Negeri Jakarta Utara,pertama,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...,Alternatif,permufakataan jahat dengan sengaja melakukan k...,Terbukti,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1005_PID~SUS_2020_PN JKT~BRT.json,1005/Pid. Sus/2020/PN. Jkt. Brt,1005/Pid. Sus/2020/PN. Jkt. Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,kajian ustadz MUHLIS\n---\nFacebook\n---\ntele...,NaN,Years: 3 | Months: 6,Tidak ada korban,NaN,NaN,NaN,NaN,NaN,NaN
2,1006_PID~SUS_2020_PN JKT~BRT.json,1006/Pid. Sus/2020/PN. Jkt. Brt,1006/Pid. Sus/2020/PN. Jkt. Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,grup Media Sosial Whats App MENITI TAUHID\n---...,NaN,Years: 3 | Months: 6,Tidak ada korban,1.0,NaN,NaN,NaN,NaN,NaN
3,1012_PID~SUS_2021_PN JKT~TIM.json,1012 Pid. SUS/2021/PN. Jkt. Tim,1012 Pid. SUS/2021/PN. Jkt. Tim,Pengadilan Negeri Jakarta Timur sejak,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,NaN,Tindak Pidana Terorisme,Terbukti,NaN,...,kajian Diniyah di Mushola daerah Ds. Pondok Su...,keinginan untuk hidup dibawah naungan Negara S...,Years: 3 | Months: 6,Tidak ada korban,NaN,Rumah Tahanan Negara (RUTAN),NaN,NaN,NaN,NaN
4,1014_PID~SUS_2021_PN JKT~TIM.json,1014/Pid. Sus/2021/PN Jkt. Tim,1014/Pid. Sus/2021/PN Jkt. Tim,Pengadilan Negeri Jakarta Timur,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Kombinasi,tindak pidana Terorisme dan Pendanaan Terorisme,Primair: Terbukti,NaN,...,NaN,NaN,Years: 4 | Months: 6,Tidak ada korban,1.0,NaN,50.000.000,NaN,NaN,NaN

In [47]:
df_filtered = data[["why_mitigating_factors", "File_Name"]]
df_filtered.head()

,why_mitigating_factors,File_Name
0,NaN,02_PID~ SUS~_2014_PN~JKT~ UT~.json
1,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,1005_PID~SUS_2020_PN JKT~BRT.json
2,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,1006_PID~SUS_2020_PN JKT~BRT.json
3,Terdakwa bersikap sopan dipersidangan\n---\nTe...,1012_PID~SUS_2021_PN JKT~TIM.json
4,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,1014_PID~SUS_2021_PN JKT~TIM.json

In [50]:
unknown_mitigating = df_filtered[
    (df_filtered["why_mitigating_factors"] == "Tidak Diketahui") |
    (df_filtered["why_mitigating_factors"].isna())
]

print(len(unknown_ideology))

222

In [51]:
unknown_mitigating.to_excel("unknown_mitigating.xlsx", index=False)

## Unknown Charge Articles

In [3]:
data = pd.read_excel("rekap_data_terorisme_loc_v6.xlsx")
data.head()

,File_Name,case_id,what_case_number,what_court_name,what_court_level,what_charged_articles,what_indictment_model,what_proven_offense,what_verdict_per_charge,what_appellate_outcome,...,why_radicalization_sources,why_motivation_factors,how_much_prison_term,how_much_injury_severity,what_detention_credit,where_detention_location,how_much_monetary_penalties,what_is_imputed_articles,how_much_seized_money_amount,when_indictment_date
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,02/Pid. Sus./2014/PN. Jkt. Ut,02/Pid. Sus./2014/PN. Jkt. Ut,Pengadilan Negeri Jakarta Utara,pertama,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...,Alternatif,permufakataan jahat dengan sengaja melakukan k...,Terbukti,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1005_PID~SUS_2020_PN JKT~BRT.json,1005/Pid. Sus/2020/PN. Jkt. Brt,1005/Pid. Sus/2020/PN. Jkt. Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,kajian ustadz MUHLIS\n---\nFacebook\n---\ntele...,NaN,Years: 3 | Months: 6,Tidak ada korban,NaN,NaN,NaN,NaN,NaN,NaN
2,1006_PID~SUS_2020_PN JKT~BRT.json,1006/Pid. Sus/2020/PN. Jkt. Brt,1006/Pid. Sus/2020/PN. Jkt. Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,grup Media Sosial Whats App MENITI TAUHID\n---...,NaN,Years: 3 | Months: 6,Tidak ada korban,True,NaN,NaN,NaN,NaN,NaN
3,1012_PID~SUS_2021_PN JKT~TIM.json,1012 Pid. SUS/2021/PN. Jkt. Tim,1012 Pid. SUS/2021/PN. Jkt. Tim,Pengadilan Negeri Jakarta Timur sejak,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,NaN,Tindak Pidana Terorisme,Terbukti,NaN,...,kajian Diniyah di Mushola daerah Ds. Pondok Su...,keinginan untuk hidup dibawah naungan Negara S...,Years: 3 | Months: 6,Tidak ada korban,NaN,Rumah Tahanan Negara (RUTAN),NaN,NaN,NaN,NaN
4,1014_PID~SUS_2021_PN JKT~TIM.json,1014/Pid. Sus/2021/PN Jkt. Tim,1014/Pid. Sus/2021/PN Jkt. Tim,Pengadilan Negeri Jakarta Timur,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Kombinasi,tindak pidana Terorisme dan Pendanaan Terorisme,Primair: Terbukti,NaN,...,NaN,NaN,Years: 4 | Months: 6,Tidak ada korban,True,NaN,50.000.000,NaN,NaN,NaN

In [5]:
df_filtered = data[["File_Name", "what_charged_articles"]]
df_filtered.head()

,File_Name,what_charged_articles
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...
1,1005_PID~SUS_2020_PN JKT~BRT.json,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...
2,1006_PID~SUS_2020_PN JKT~BRT.json,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...
3,1012_PID~SUS_2021_PN JKT~TIM.json,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...
4,1014_PID~SUS_2021_PN JKT~TIM.json,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...

In [6]:
unknown_charge = df_filtered[
    (df_filtered["what_charged_articles"].isna())
]

print(len(unknown_charge))

44

In [5]:
unknown_charge.to_excel("unknown_charge.xlsx", index=False)

## Unknown case number

In [10]:
data = pd.read_excel("rekap_data_terorisme_loc_v7.xlsx")
data.head()

,File_Name,case_id,what_case_number,what_court_name,what_court_level,what_charged_articles,what_indictment_model,what_proven_offense,what_verdict_per_charge,what_appellate_outcome,...,why_radicalization_sources,why_motivation_factors,how_much_prison_term,how_much_injury_severity,what_detention_credit,where_detention_location,how_much_monetary_penalties,what_is_imputed_articles,how_much_seized_money_amount,when_indictment_date
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,02/Pid. Sus./2014/PN. Jkt. Ut,02/Pid. Sus./2014/PN. Jkt. Ut,Pengadilan Negeri Jakarta Utara,pertama,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...,Alternatif,permufakataan jahat dengan sengaja melakukan k...,Terbukti,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1005_PID~SUS_2020_PN JKT~BRT.json,1005/Pid. Sus/2020/PN. Jkt. Brt,1005/Pid. Sus/2020/PN. Jkt. Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,kajian ustadz MUHLIS\n---\nFacebook\n---\ntele...,NaN,Years: 3 | Months: 6,Tidak ada korban,NaN,NaN,NaN,NaN,NaN,NaN
2,1006_PID~SUS_2020_PN JKT~BRT.json,1006/Pid. Sus/2020/PN. Jkt. Brt,1006/Pid. Sus/2020/PN. Jkt. Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,grup Media Sosial Whats App MENITI TAUHID\n---...,NaN,Years: 3 | Months: 6,Tidak ada korban,True,NaN,NaN,NaN,NaN,NaN
3,1012_PID~SUS_2021_PN JKT~TIM.json,1012 Pid. SUS/2021/PN. Jkt. Tim,1012 Pid. SUS/2021/PN. Jkt. Tim,Pengadilan Negeri Jakarta Timur sejak,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,NaN,Tindak Pidana Terorisme,Terbukti,NaN,...,kajian Diniyah di Mushola daerah Ds. Pondok Su...,keinginan untuk hidup dibawah naungan Negara S...,Years: 3 | Months: 6,Tidak ada korban,NaN,Rumah Tahanan Negara (RUTAN),NaN,NaN,NaN,NaN
4,1014_PID~SUS_2021_PN JKT~TIM.json,1014/Pid. Sus/2021/PN Jkt. Tim,1014/Pid. Sus/2021/PN Jkt. Tim,Pengadilan Negeri Jakarta Timur,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Kombinasi,tindak pidana Terorisme dan Pendanaan Terorisme,Primair: Terbukti,NaN,...,NaN,NaN,Years: 4 | Months: 6,Tidak ada korban,True,NaN,50.000.000,NaN,NaN,NaN

In [11]:
df_filtered = data[["File_Name", "case_id", "what_case_number"]]
df_filtered

,File_Name,case_id,what_case_number
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,02/Pid. Sus./2014/PN. Jkt. Ut,02/Pid. Sus./2014/PN. Jkt. Ut
1,1005_PID~SUS_2020_PN JKT~BRT.json,1005/Pid. Sus/2020/PN. Jkt. Brt,1005/Pid. Sus/2020/PN. Jkt. Brt
2,1006_PID~SUS_2020_PN JKT~BRT.json,1006/Pid. Sus/2020/PN. Jkt. Brt,1006/Pid. Sus/2020/PN. Jkt. Brt
3,1012_PID~SUS_2021_PN JKT~TIM.json,1012 Pid. SUS/2021/PN. Jkt. Tim,1012 Pid. SUS/2021/PN. Jkt. Tim
4,1014_PID~SUS_2021_PN JKT~TIM.json,1014/Pid. Sus/2021/PN Jkt. Tim,1014/Pid. Sus/2021/PN Jkt. Tim
...,...,...,...
510,putusan_303_pid.sus_2019_pn_jkt.utr_2025122100...,303/Pid. Sus. Teroris/2019/PN Jkt. Utr,303/Pid. Sus. Teroris/2019/PN Jkt. Utr
511,putusan_373_pid.sus.teroris_2015_pn.jkt.utr._2...,373/Pid. Sus. Teroris/2015/PN. Jkt. Utr,373/Pid. Sus. Teroris/2015/PN. Jkt. Utr
512,putusan_459_pid.sus_2019_pn_jkt.utr_2026012014...,459/Pid. Sus. Teroris/2019/PN Jkt. Utr,459/Pid. Sus. Teroris/2019/PN Jkt. Utr
513,putusan_461_pid.sus_2019_pn_jkt.utr_2026012014...,461/Pid. Sus-Teroris/2019/PN. Jkt. Utr,461/Pid. Sus-Teroris/2019/PN. Jkt. Utr
514,putusan_620_pid.sus_2018_pn_.jkt_utr_202601201...,620/Pid. Sus/2018/PN. Jkt Utr,620/Pid. Sus/2018/PN. Jkt Utr

In [12]:
df_filtered.to_excel("check_case_number_2.xlsx")

### Court Location and District Court (Unknown)

In [9]:
data = pd.read_excel("rekap_data_terorisme_loc_v8.xlsx")
data.head()

,File_Name,case_id,what_case_number,what_court_name,what_court_level,what_charged_articles,what_indictment_model,what_proven_offense,what_verdict_per_charge,what_appellate_outcome,...,why_radicalization_sources,why_motivation_factors,how_much_prison_term,how_much_injury_severity,what_detention_credit,where_detention_location,how_much_monetary_penalties,what_is_imputed_articles,how_much_seized_money_amount,when_indictment_date
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,02/Pid.Sus./2014/PN.Jkt.Ut,02/Pid.Sus./2014/PN.Jkt.Ut,Pengadilan Negeri Jakarta Utara,pertama,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...,Alternatif,permufakataan jahat dengan sengaja melakukan k...,Terbukti,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1005_PID~SUS_2020_PN JKT~BRT.json,1005/Pid.Sus/2020/PN.Jkt.Brt,1005/Pid.Sus/2020/PN.Jkt.Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,kajian ustadz MUHLIS\n---\nFacebook\n---\ntele...,NaN,Years: 3 | Months: 6,Tidak ada korban,NaN,NaN,NaN,NaN,NaN,NaN
2,1006_PID~SUS_2020_PN JKT~BRT.json,1006/Pid.Sus/2020/PN.Jkt.Brt,1006/Pid.Sus/2020/PN.Jkt.Brt,Pengadilan Negeri Jakarta Barat,pertama,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...,Alternatif,Tindak Pidana Terorisme,Terbukti,NaN,...,grup Media Sosial Whats App MENITI TAUHID\n---...,NaN,Years: 3 | Months: 6,Tidak ada korban,True,NaN,NaN,NaN,NaN,NaN
3,1012_PID~SUS_2021_PN JKT~TIM.json,1012Pid.SUS/2021/PN.Jkt.Tim,1012Pid.SUS/2021/PN.Jkt.Tim,Pengadilan Negeri Jakarta Timur,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,NaN,Tindak Pidana Terorisme,Terbukti,NaN,...,kajian Diniyah di Mushola daerah Ds. Pondok Su...,keinginan untuk hidup dibawah naungan Negara S...,Years: 3 | Months: 6,Tidak ada korban,NaN,Rumah Tahanan Negara (RUTAN),NaN,NaN,NaN,NaN
4,1014_PID~SUS_2021_PN JKT~TIM.json,1014/Pid.Sus/2021/PNJkt.Tim,1014/Pid.Sus/2021/PNJkt.Tim,Pengadilan Negeri Jakarta Timur,pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,Kombinasi,tindak pidana Terorisme dan Pendanaan Terorisme,Primair: Terbukti,NaN,...,NaN,NaN,Years: 4 | Months: 6,Tidak ada korban,True,NaN,50.000.000,NaN,NaN,NaN

In [10]:
data.columns

Index(['File_Name', 'case_id', 'what_case_number', 'what_court_name',
       'what_court_level', 'what_charged_articles', 'what_indictment_model',
       'what_proven_offense', 'what_verdict_per_charge',
       'what_appellate_outcome', 'what_evidence_items',
       'what_evidence_disposition', 'what_defense_plea',
       'what_pelatihan_activities', 'what_perencanaan_activities',
       'what_tindakan_activities', 'what_normalized_articles',
       'when_appeal_timeline', 'when_arrest_date', 'when_crime_time_range',
       'when_detention_timeline', 'when_district_court_date',
       'when_tahun_putusan', 'when_bulan_putusan', 'when_tahun_penangkapan',
       'when_lag_bulan', 'where_district_court', 'where_court_location',
       'where_normalized_court_province', 'where_normalized_court_city',
       'where_normalized_court_code', 'who_defendants', 'who_co_defendants',
       'who_defense_counsels', 'who_investigators', 'who_judges', 'who_clerk',
       'who_prosecutors', 'who_witnesses',
       'who_defendant_ideology_affiliation', 'who_provinsi_jaringan',
       'who_kota_jaringan', 'who_normalized_defense_counsels',
       'who_normalized_judges', 'who_normalized_clerk',
       'who_normalized_prosecutors', 'who_normalized_co_defendants',
       'why_reasoning_evidence', 'why_reasoning_appeal',
       'why_classified_radicalization_sources', 'why_radicalization_channel',
       'why_classified_motivation_factors',
       'why_classified_aggravating_factors', 'how_many_witness_count',
       'how_many_charge_count', 'how_many_defendant_count',
       'how_many_evidence_item_count', 'what_has_attack_plan',
       'what_attack_preparation_activities', 'what_attack_plan_summary',
       'what_defendant_chat_platform',
       'when_defendant_local_network_joined_at', 'where_activity_locations',
       'where_crime_location', 'where_arrest_location',
       'who_defendant_local_network', 'who_related_entities',
       'why_aggravating_factors', 'why_mitigating_factors',
       'why_radicalization_sources', 'why_motivation_factors',
       'how_much_prison_term', 'how_much_injury_severity',
       'what_detention_credit', 'where_detention_location',
       'how_much_monetary_penalties', 'what_is_imputed_articles',
       'how_much_seized_money_amount', 'when_indictment_date'],
      dtype='str')

In [11]:
df_court = data[["File_Name", "what_court_name", "where_court_location", "where_district_court"]]
df_court

,File_Name,what_court_name,where_court_location,where_district_court
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,Pengadilan Negeri Jakarta Utara,Jakarta Utara,Pengadilan Negeri Jakarta Utara
1,1005_PID~SUS_2020_PN JKT~BRT.json,Pengadilan Negeri Jakarta Barat,Jakarta Barat,Pengadilan Negeri Jakarta Barat
2,1006_PID~SUS_2020_PN JKT~BRT.json,Pengadilan Negeri Jakarta Barat,Jakarta Barat,Pengadilan Negeri Jakarta Barat
3,1012_PID~SUS_2021_PN JKT~TIM.json,Pengadilan Negeri Jakarta Timur,Jakarta Timur,Pengadilan Negeri Jakarta Timur
4,1014_PID~SUS_2021_PN JKT~TIM.json,Pengadilan Negeri Jakarta Timur,Jakarta Timur,Pengadilan Negeri Jakarta Timur
...,...,...,...,...
510,putusan_303_pid.sus_2019_pn_jkt.utr_2025122100...,Pengadilan Negeri Jakarta Utara,Jakarta Utara,Pengadilan Negeri Jakarta Utara
511,putusan_373_pid.sus.teroris_2015_pn.jkt.utr._2...,Pengadilan Negeri Jakarta Utara,Jakarta Utara,Pengadilan Negeri Jakarta Utara
512,putusan_459_pid.sus_2019_pn_jkt.utr_2026012014...,Pengadilan Negeri Jakarta Utara,Jakarta Utara,Pengadilan Negeri Jakarta Utara
513,putusan_461_pid.sus_2019_pn_jkt.utr_2026012014...,Pengadilan Negeri Jakarta Utara,Jakarta Utara,Pengadilan Negeri Jakarta Utara
514,putusan_620_pid.sus_2018_pn_.jkt_utr_202601201...,Pengadilan Negeri Jakarta Utara,Jakarta Utara,Pengadilan Negeri Jakarta Utara

In [12]:
df_court.to_excel("check_court_location_district_2.xlsx")

## Cases Normalization

In [2]:
data = pd.read_excel("rekap_data_terorisme_loc_v8.xlsx")
data.head()

,File_Name,case_id,what_case_number,what_court_name,what_court_level,what_charged_articles,what_indictment_model,what_proven_offense,what_verdict_per_charge,what_appellate_outcome,...,why_mitigating_factors,why_radicalization_sources,why_motivation_factors,how_much_prison_term,how_much_injury_severity,where_detention_location,how_much_monetary_penalties,what_is_imputed_articles,how_much_seized_money_amount,when_indictment_date
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,02/Pid.Sus./2014/PN.Jkt.Ut,02/Pid.Sus./2014/PN.Jkt.Ut,Pengadilan Negeri Jakarta Utara,tingkat pertama,Pasal 15 Jo. Pasal 6 Perpu No. 1 Tahun 2002\n-...,alternatif,permufakataan jahat dengan sengaja melakukan k...,convicted,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1005_PID~SUS_2020_PN JKT~BRT.json,1005/Pid.Sus/2020/PN.Jkt.Brt,1005/Pid.Sus/2020/PN.Jkt.Brt,Pengadilan Negeri Jakarta Barat,tingkat pertama,Pasal 15 Jo Pasal 7 Undang-Undang Republik Ind...,alternatif,Tindak Pidana Terorisme,convicted,NaN,...,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,kajian ustadz MUHLIS\n---\nFacebook\n---\ntele...,NaN,Years: 3 | Months: 6,Tidak ada korban,NaN,NaN,NaN,NaN,NaN
2,1006_PID~SUS_2020_PN JKT~BRT.json,1006/Pid.Sus/2020/PN.Jkt.Brt,1006/Pid.Sus/2020/PN.Jkt.Brt,Pengadilan Negeri Jakarta Barat,tingkat pertama,Pasal 15 jo Pasal 7 Undang-Undang Republik Ind...,alternatif,Tindak Pidana Terorisme,convicted,NaN,...,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,grup Media Sosial Whats App MENITI TAUHID\n---...,NaN,Years: 3 | Months: 6,Tidak ada korban,NaN,NaN,NaN,NaN,NaN
3,1012_PID~SUS_2021_PN JKT~TIM.json,1012Pid.SUS/2021/PN.Jkt.Tim,1012Pid.SUS/2021/PN.Jkt.Tim,Pengadilan Negeri Jakarta Timur,tingkat pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,tidak diketahui,Tindak Pidana Terorisme,convicted,NaN,...,Terdakwa bersikap sopan dipersidangan\n---\nTe...,kajian Diniyah di Mushola daerah Ds. Pondok Su...,keinginan untuk hidup dibawah naungan Negara S...,Years: 3 | Months: 6,Tidak ada korban,Rumah Tahanan Negara (RUTAN),NaN,NaN,NaN,NaN
4,1014_PID~SUS_2021_PN JKT~TIM.json,1014/Pid.Sus/2021/PNJkt.Tim,1014/Pid.Sus/2021/PNJkt.Tim,Pengadilan Negeri Jakarta Timur,tingkat pertama,Pasal 15 jo. Pasal 7 Peraturan Pemerintah Peng...,kombinasi,tindak pidana Terorisme dan Pendanaan Terorisme,convicted,NaN,...,Terdakwa belum pernah dihukum\n---\nTerdakwa m...,NaN,NaN,Years: 4 | Months: 6,Tidak ada korban,NaN,50.000.000,NaN,NaN,NaN

In [3]:
data.columns

Index(['File_Name', 'case_id', 'what_case_number', 'what_court_name',
       'what_court_level', 'what_charged_articles', 'what_indictment_model',
       'what_proven_offense', 'what_verdict_per_charge',
       'what_appellate_outcome', 'what_evidence_items',
       'what_evidence_disposition', 'what_defense_plea',
       'what_pelatihan_activities', 'what_perencanaan_activities',
       'what_tindakan_activities', 'what_normalized_articles',
       'what_detention_credit', 'what_attack_plan_summary',
       'when_appeal_timeline', 'when_arrest_date', 'when_crime_time_range',
       'when_detention_timeline', 'when_district_court_date',
       'when_tahun_putusan', 'when_bulan_putusan', 'when_tahun_penangkapan',
       'when_lag_bulan', 'where_district_court', 'where_court_location',
       'where_normalized_court_province', 'where_normalized_court_city',
       'where_normalized_court_code', 'who_defendants', 'who_co_defendants',
       'who_defense_counsels', 'who_investigators', 'who_judges', 'who_clerk',
       'who_prosecutors', 'who_witnesses',
       'who_defendant_ideology_affiliation', 'who_provinsi_jaringan',
       'who_kota_jaringan', 'who_normalized_defense_counsels',
       'who_normalized_judges', 'who_normalized_clerk',
       'who_normalized_prosecutors', 'who_normalized_co_defendants',
       'why_reasoning_evidence', 'why_reasoning_appeal',
       'why_classified_radicalization_sources', 'why_radicalization_channel',
       'why_classified_motivation_factors',
       'why_classified_aggravating_factors', 'how_much_prison_term_years',
       'how_much_prison_term_months', 'how_many_witness_count',
       'how_many_charge_count', 'how_many_defendant_count',
       'how_many_evidence_item_count', 'what_has_attack_plan',
       'what_attack_preparation_activities', 'what_defendant_chat_platform',
       'when_defendant_local_network_joined_at', 'where_activity_locations',
       'where_crime_location', 'where_arrest_location',
       'who_defendant_local_network', 'who_related_entities',
       'why_aggravating_factors', 'why_mitigating_factors',
       'why_radicalization_sources', 'why_motivation_factors',
       'how_much_prison_term', 'how_much_injury_severity',
       'where_detention_location', 'how_much_monetary_penalties',
       'what_is_imputed_articles', 'how_much_seized_money_amount',
       'when_indictment_date'],
      dtype='str')

In [4]:
# filtered_data = data[["File_Name", "what_case_number", "what_court_level", "what_indictment_model", "what_verdict_per_charge", "how_much_prison_term", "what_detention_credit", "when_indictment_date", 
#                       "when_arrest_date", "when_detention_timeline", "when_appeal_timeline", "why_aggravating_factors", "why_mitigating_factors", "what_has_attack_plan", "what_attack_plan_summary",
#                       "why_motivation_factors"]]

filtered_data = data[["File_Name", "what_case_number", "when_arrest_date", "when_appeal_timeline", "when_district_court_date", "what_has_attack_plan", "what_attack_plan_summary"]]

In [5]:
filtered_data.head()

,File_Name,what_case_number,when_arrest_date,when_appeal_timeline,when_district_court_date,what_has_attack_plan,what_attack_plan_summary
0,02_PID~ SUS~_2014_PN~JKT~ UT~.json,02/Pid.Sus./2014/PN.Jkt.Ut,2013-08-28,tidak diketahui,NaN,NaN,tidak diketahui
1,1005_PID~SUS_2020_PN JKT~BRT.json,1005/Pid.Sus/2020/PN.Jkt.Brt,2019-11-04,tidak diketahui,2020-09-14,False,tidak diketahui
2,1006_PID~SUS_2020_PN JKT~BRT.json,1006/Pid.Sus/2020/PN.Jkt.Brt,2019-10-26,tidak diketahui,2020-10-12,True,Penyerangan terhadap Kantor Polisi di Pare Ked...
3,1012_PID~SUS_2021_PN JKT~TIM.json,1012Pid.SUS/2021/PN.Jkt.Tim,2021-04-10,tidak diketahui,2022-03-30,False,tidak diketahui
4,1014_PID~SUS_2021_PN JKT~TIM.json,1014/Pid.Sus/2021/PNJkt.Tim,2021-04-12,tidak diketahui,2022-03-07,False,tidak diketahui

In [6]:
filtered_data.to_excel("cases_analysis_3.xlsx")

In [7]:
indictment_date = filtered_data[
    (filtered_data["when_appeal_timeline"].isna())
]

print(len(indictment_date))

0